import { Sku } from '.'

let sku

beforeEach(async () => {
  sku = await Sku.create({ MCId: 'test', MCCode: 'test', SMCId: 'test', SMCCode: 'test', MId: 'test', MCode: 'test', AGId: 'test', AGCode: 'test', MakeId: 'test', MakeCode: 'test', MakeImage: 'test', SKUCode: 'test', SKUDescription: 'test', image: 'test', : 'test', mType: 'test', EBSKU: 'test', EBSKUId: 'test', targetLvl: 'test', reorderLvl: 'test', reorderQty: 'test', isActive: 'test' })
})

describe('view', () => {
  it('returns simple view', () => {
    const view = sku.view()
    expect(typeof view).toBe('object')
    expect(view.id).toBe(sku.id)
    expect(view.MCId).toBe(sku.MCId)
    expect(view.MCCode).toBe(sku.MCCode)
    expect(view.SMCId).toBe(sku.SMCId)
    expect(view.SMCCode).toBe(sku.SMCCode)
    expect(view.MId).toBe(sku.MId)
    expect(view.MCode).toBe(sku.MCode)
    expect(view.AGId).toBe(sku.AGId)
    expect(view.AGCode).toBe(sku.AGCode)
    expect(view.MakeId).toBe(sku.MakeId)
    expect(view.MakeCode).toBe(sku.MakeCode)
    expect(view.MakeImage).toBe(sku.MakeImage)
    expect(view.SKUCode).toBe(sku.SKUCode)
    expect(view.SKUDescription).toBe(sku.SKUDescription)
    expect(view.image).toBe(sku.image)
    expect(view.).toBe(sku.)
    expect(view.mType).toBe(sku.mType)
    expect(view.EBSKU).toBe(sku.EBSKU)
    expect(view.EBSKUId).toBe(sku.EBSKUId)
    expect(view.targetLvl).toBe(sku.targetLvl)
    expect(view.reorderLvl).toBe(sku.reorderLvl)
    expect(view.reorderQty).toBe(sku.reorderQty)
    expect(view.isActive).toBe(sku.isActive)
    expect(view.createdAt).toBeTruthy()
    expect(view.updatedAt).toBeTruthy()
  })

  it('returns full view', () => {
    const view = sku.view(true)
    expect(typeof view).toBe('object')
    expect(view.id).toBe(sku.id)
    expect(view.MCId).toBe(sku.MCId)
    expect(view.MCCode).toBe(sku.MCCode)
    expect(view.SMCId).toBe(sku.SMCId)
    expect(view.SMCCode).toBe(sku.SMCCode)
    expect(view.MId).toBe(sku.MId)
    expect(view.MCode).toBe(sku.MCode)
    expect(view.AGId).toBe(sku.AGId)
    expect(view.AGCode).toBe(sku.AGCode)
    expect(view.MakeId).toBe(sku.MakeId)
    expect(view.MakeCode).toBe(sku.MakeCode)
    expect(view.MakeImage).toBe(sku.MakeImage)
    expect(view.SKUCode).toBe(sku.SKUCode)
    expect(view.SKUDescription).toBe(sku.SKUDescription)
    expect(view.image).toBe(sku.image)
    expect(view.).toBe(sku.)
    expect(view.mType).toBe(sku.mType)
    expect(view.EBSKU).toBe(sku.EBSKU)
    expect(view.EBSKUId).toBe(sku.EBSKUId)
    expect(view.targetLvl).toBe(sku.targetLvl)
    expect(view.reorderLvl).toBe(sku.reorderLvl)
    expect(view.reorderQty).toBe(sku.reorderQty)
    expect(view.isActive).toBe(sku.isActive)
    expect(view.createdAt).toBeTruthy()
    expect(view.updatedAt).toBeTruthy()
  })
})
