import { Parties } from '.'

let parties

beforeEach(async () => {
  parties = await Parties.create({ userId: 'test', name: 'test', partyType: 'test', organizationName: 'test', PartyRoleId: 'test', PartyelRole: 'test', PAN: 'test', TAN: 'test', GSTIN: 'test', addressTypeId: 'test', addressType: 'test', contactId: 'test', UIDAI: 'test', ESINumber: 'test', EPFNumber: 'test', DLNo: 'test', bloodGroup: 'test', physicalFitnness: 'test' })
})

describe('view', () => {
  it('returns simple view', () => {
    const view = parties.view()
    expect(typeof view).toBe('object')
    expect(view.id).toBe(parties.id)
    expect(view.userId).toBe(parties.userId)
    expect(view.name).toBe(parties.name)
    expect(view.partyType).toBe(parties.partyType)
    expect(view.organizationName).toBe(parties.organizationName)
    expect(view.PartyRoleId).toBe(parties.PartyRoleId)
    expect(view.PartyelRole).toBe(parties.PartyelRole)
    expect(view.PAN).toBe(parties.PAN)
    expect(view.TAN).toBe(parties.TAN)
    expect(view.GSTIN).toBe(parties.GSTIN)
    expect(view.addressTypeId).toBe(parties.addressTypeId)
    expect(view.addressType).toBe(parties.addressType)
    expect(view.contactId).toBe(parties.contactId)
    expect(view.UIDAI).toBe(parties.UIDAI)
    expect(view.ESINumber).toBe(parties.ESINumber)
    expect(view.EPFNumber).toBe(parties.EPFNumber)
    expect(view.DLNo).toBe(parties.DLNo)
    expect(view.bloodGroup).toBe(parties.bloodGroup)
    expect(view.physicalFitnness).toBe(parties.physicalFitnness)
    expect(view.createdAt).toBeTruthy()
    expect(view.updatedAt).toBeTruthy()
  })

  it('returns full view', () => {
    const view = parties.view(true)
    expect(typeof view).toBe('object')
    expect(view.id).toBe(parties.id)
    expect(view.userId).toBe(parties.userId)
    expect(view.name).toBe(parties.name)
    expect(view.partyType).toBe(parties.partyType)
    expect(view.organizationName).toBe(parties.organizationName)
    expect(view.PartyRoleId).toBe(parties.PartyRoleId)
    expect(view.PartyelRole).toBe(parties.PartyelRole)
    expect(view.PAN).toBe(parties.PAN)
    expect(view.TAN).toBe(parties.TAN)
    expect(view.GSTIN).toBe(parties.GSTIN)
    expect(view.addressTypeId).toBe(parties.addressTypeId)
    expect(view.addressType).toBe(parties.addressType)
    expect(view.contactId).toBe(parties.contactId)
    expect(view.UIDAI).toBe(parties.UIDAI)
    expect(view.ESINumber).toBe(parties.ESINumber)
    expect(view.EPFNumber).toBe(parties.EPFNumber)
    expect(view.DLNo).toBe(parties.DLNo)
    expect(view.bloodGroup).toBe(parties.bloodGroup)
    expect(view.physicalFitnness).toBe(parties.physicalFitnness)
    expect(view.createdAt).toBeTruthy()
    expect(view.updatedAt).toBeTruthy()
  })
})
